// <auto-generated />
using System;
using Gestion_de_Musica.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gestion_de_Musica.Migrations
{
    [DbContext(typeof(MusicaDbContext))]
    [Migration("20250919040109_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gestion_de_Musica.Models.Album", b =>
                {
                    b.Property<int>("album_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("album_id"));

                    b.Property<int?>("artista_id")
                        .HasColumnType("int");

                    b.Property<int?>("año_lanzamiento")
                        .HasColumnType("int");

                    b.Property<string>("discografica")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("genero")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("album_id");

                    b.HasIndex("artista_id");

                    b.ToTable("Albumes");
                });

            modelBuilder.Entity("Gestion_de_Musica.Models.Artista", b =>
                {
                    b.Property<int>("artista_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("artista_id"));

                    b.Property<string>("apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("fecha_creacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("fecha_nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nacionalidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("artista_id");

                    b.ToTable("Artistas");
                });

            modelBuilder.Entity("Gestion_de_Musica.Models.Album", b =>
                {
                    b.HasOne("Gestion_de_Musica.Models.Artista", "Artista")
                        .WithMany("Albumes")
                        .HasForeignKey("artista_id");

                    b.Navigation("Artista");
                });

            modelBuilder.Entity("Gestion_de_Musica.Models.Artista", b =>
                {
                    b.Navigation("Albumes");
                });
#pragma warning restore 612, 618
        }
    }
}
